$content = Get-Content 'src\pages\Admin.jsx'
$startIndex = 4063 # line 4064
$endIndex = 4135   # line 4136

$newSection = @()
$newSection += '            {/* LIST SECTION */}'
$newSection += '            {["collections", "products", "promo-codes", "blogs"].includes(activeTab) ? ('
$newSection += '                <div className="grid grid-cols-1 gap-4 md:gap-6">'
$newSection += '                    {tabsLoading[activeTab] ?'
$newSection += '                        <div className="flex items-center justify-center py-20">'
$newSection += '                            <Loader2 className="animate-spin text-black" size={32} />'
$newSection += '                        </div>'
$newSection += '                    :'
$newSection += '                        (activeTab === "collections" ? collections : activeTab === "products" ? products : activeTab === "promo-codes" ? promoCodes : blogs).length === 0 ?'
$newSection += '                            <div className="text-center py-20 text-black/40 tracking-widest uppercase text-xs bg-neutral-50 border border-black/5">No records found</div>'
$newSection += '                        :'
$newSection += '                            (activeTab === "collections" ? collections : activeTab === "products" ? products : activeTab === "promo-codes" ? promoCodes : blogs).map(item => ('
# Corrected item structure
$newSection += '                                <div key={item.id} className="bg-white border border-black/5 p-6 md:p-8 hover:border-black/20 transition-all group">'
$newSection += '                                    <div className="flex flex-col md:flex-row items-start md:items-center gap-6 md:gap-10">'
$newSection += '                                        <div className="w-full md:w-32 h-48 md:h-32 overflow-hidden bg-neutral-50 flex-shrink-0 border border-black/5 flex items-center justify-center group relative">'
$newSection += '                                            {activeTab === "promo-codes" ? ('
$newSection += '                                                <Ticket size={32} className="text-black/10" />'
$newSection += '                                            ) : ('
$newSection += '                                                <img src={getFullImageUrl(item.banner_url || item.image_url)} alt="" className="w-full h-full object-cover opacity-90 group-hover:opacity-100 group-hover:scale-110 transition-all duration-1000" />'
$newSection += '                                            )}'
$newSection += '                                        </div>'
$newSection += ''
$newSection += '                                        <div className="flex-grow space-y-4 w-full">'
$newSection += '                                            <div className="flex flex-col sm:flex-row justify-between items-start gap-4">'
$newSection += '                                                <div>'
$newSection += '                                                    <h3 className="text-sm md:text-base tracking-[0.15em] text-black uppercase mb-1">{item.name || item.title || item.code}</h3>'
$newSection += '                                                    <div className="flex flex-col">'
$newSection += '                                                        <div className="flex flex-wrap items-center gap-3">'
$newSection += '                                                            <p className="text-[10px] tracking-[0.15em] text-black uppercase font-black">'
$newSection += '                                                                {activeTab === "collections" ? item.slug :'
$newSection += '                                                                activeTab === "products" ? `${item.collection_name}` :'
$newSection += '                                                                activeTab === "promo-codes" ? (new Date(item.expiry_date) < new Date() ? "Expired" : "Active") :'
$newSection += '                                                                `BY ${item.author || "Artisan"}`}'
$newSection += '                                                            </p>'
$newSection += '                                                            <span className="w-1 h-1 rounded-full bg-black/10" />'
$newSection += '                                                            <p className="text-[10px] tracking-[0.15em] text-black/40 uppercase font-black">'
$newSection += '                                                                {activeTab === "collections" ? "Primary Collection" :'
$newSection += '                                                                activeTab === "products" ? `₹${item.price} | Stock: ${item.stock_count || 0}` :'
$newSection += '                                                                activeTab === "promo-codes" ? `${item.discount_type === "percentage" ? item.discount_value + "%" : "₹" + item.discount_value} OFF | Used: ${item.usage_count}/${item.usage_limit || "∞"}` :'
$newSection += '                                                                `${new Date(item.created_at).toLocaleDateString()}`}'
$newSection += '                                                            </p>'
$newSection += '                                                        </div>'
$newSection += '                                                        {activeTab === "promo-codes" && ('
$newSection += '                                                            <div className="flex gap-4 mt-3">'
$newSection += '                                                                <p className="text-[8px] text-black/40 uppercase tracking-widest font-black">Expires: {new Date(item.expiry_date).toLocaleDateString()}</p>'
$newSection += '                                                                <p className="text-[8px] text-black/40 uppercase tracking-widest font-black">Min Order: ₹{item.min_order_amount || 0}</p>'
$newSection += '                                                            </div>'
$newSection += '                                                        )}'
$newSection += '                                                    </div>'
$newSection += '                                                </div>'
$newSection += '                                                <div className="flex items-center gap-4 w-full sm:w-auto pt-4 sm:pt-0 border-t border-black/5 sm:border-none">'
$newSection += '                                                    <button onClick={() => handleEdit(activeTab, item)} className="flex-1 sm:flex-none bg-neutral-50 border border-black/10 px-5 py-3 text-[9px] uppercase tracking-widest text-black hover:bg-black hover:text-white transition-all flex items-center justify-center gap-2">'
$newSection += '                                                        <Edit3 size={14} /> Edit'
$newSection += '                                                    </button>'
$newSection += '                                                    <button onClick={() => handleDelete(activeTab === "blogs" ? "blogs" : activeTab, item.id)} className="flex-1 sm:flex-none bg-red-600/5 border border-red-600/10 px-5 py-3 text-[9px] uppercase tracking-widest text-red-600/70 hover:bg-red-600 hover:text-white transition-all flex items-center justify-center gap-2">'
$newSection += '                                                        <Trash2 size={14} /> Remove'
$newSection += '                                                    </button>'
$newSection += '                                                </div>'
$newSection += '                                            </div>'
$newSection += '                                            {activeTab === "blogs" && ('
$newSection += '                                                <p className="text-[11px] text-black/40 line-clamp-2 font-serif leading-relaxed max-w-3xl">'
$newSection += '                                                    {item.content?.replace(/<[^>]*>/g, "").substring(0, 180)}...'
$newSection += '                                                </p>'
$newSection += '                                            )}'
$newSection += '                                        </div>'
$newSection += '                                    </div>'
$newSection += '                                </div>'
$newSection += '                            ))'
$newSection += '                    }'
$newSection += '                </div>'
$newSection += '            ) : null}'

$finalContent = $content[0..4062] + $newSection + $content[4136..($content.Length - 1)]
$finalContent | Set-Content 'src\pages\Admin.jsx'
